version: '3.1'

services:
  service:
    image: 'docker.io/evkuzin/file_to_hashring:${DOCKER_TAG}'
    command: -c /config.yaml
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config.yaml
  postgres5432:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d
  postgres5433:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d
  postgres5434:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d
  postgres5435:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d
  postgres5436:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d
  postgres5437:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5437:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./misc/sql:/docker-entrypoint-initdb.d
